"""Render deliberate, local neural narration for the Cutover demo.

The model and voice weights are downloaded separately into work/voice-model.
No product or Bob claim is generated by this script; the final text must be
checked against the actual event-period evidence before recording.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import soundfile as sf
from kokoro_onnx import Kokoro


def render_segments(
    model: Path, voices: Path, script: Path, output: Path, voice: str, speed: float
) -> list[dict[str, object]]:
    data = json.loads(script.read_text(encoding="utf-8"))
    segments = data["segments"]
    if not segments or any(not item.get("text", "").strip() for item in segments):
        raise ValueError("Every narration segment needs actual, reviewed text")
    if any("PENDING" in item["text"] or "TODO" in item["text"] for item in segments):
        raise ValueError("Replace pending narration before rendering")

    synthesizer = Kokoro(str(model), str(voices))
    timeline: np.ndarray | None = None
    rate: int | None = None
    last_end = 0
    timings: list[dict[str, object]] = []

    for item in segments:
        start = float(item["start_sec"])
        if start < 0:
            raise ValueError("Narration start times must be nonnegative")
        samples, sample_rate = synthesizer.create(
            item["text"], voice=voice, speed=speed, lang="en-us"
        )
        samples = np.asarray(samples, dtype=np.float32).reshape(-1)
        if rate is None:
            rate = sample_rate
            timeline = np.zeros(round(float(data["duration_sec"]) * rate), dtype=np.float32)
        elif sample_rate != rate:
            raise ValueError("Narration segments have inconsistent sample rates")
        assert timeline is not None
        first = round(start * rate)
        last = first + len(samples)
        if last > len(timeline):
            raise ValueError(f"Segment {item['id']} exceeds the video duration")
        if first < last_end:
            raise ValueError(f"Segment {item['id']} overlaps another spoken segment")
        timeline[first:last] = samples
        last_end = last
        timings.append(
            {"id": item["id"], "start_sec": start, "end_sec": round(last / rate, 2)}
        )

    assert timeline is not None and rate is not None
    output.parent.mkdir(parents=True, exist_ok=True)
    sf.write(output, timeline, rate, subtype="PCM_16")
    output.with_suffix(".timings.json").write_text(
        json.dumps(timings, indent=2) + "\n", encoding="utf-8"
    )
    return timings


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--script", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--model", type=Path, default=Path("work/voice-model/kokoro-v1.0.onnx"))
    parser.add_argument("--voices", type=Path, default=Path("work/voice-model/voices-v1.0.bin"))
    parser.add_argument("--voice", default="af_heart")
    parser.add_argument("--speed", type=float, default=0.82)
    args = parser.parse_args()
    if not 0.6 <= args.speed <= 1.15:
        parser.error("--speed must be between 0.6 and 1.15")
    for timing in render_segments(
        args.model, args.voices, args.script, args.output, args.voice, args.speed
    ):
        print(f"{timing['id']}: {timing['start_sec']:.2f}-{timing['end_sec']:.2f}s")


if __name__ == "__main__":
    main()
